// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcuKNZJZB_cIMa0oqAVvgRUJXcurkZDhM',
    appId: '1:259171231904:web:18481d4242b9b4c0fd01c5',
    messagingSenderId: '259171231904',
    projectId: 'quiz-app-task-86ba1',
    authDomain: 'quiz-app-task-86ba1.firebaseapp.com',
    storageBucket: 'quiz-app-task-86ba1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATRc4ZlNDlLVFPtOoQ0mo_BRv4iGmOOUQ',
    appId: '1:259171231904:android:7afaeeb6acc43e13fd01c5',
    messagingSenderId: '259171231904',
    projectId: 'quiz-app-task-86ba1',
    storageBucket: 'quiz-app-task-86ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrCb1u-KNgDYSv5WpUh7wGPWVodnBu6A',
    appId: '1:259171231904:ios:8bcc0b10bd1d4fedfd01c5',
    messagingSenderId: '259171231904',
    projectId: 'quiz-app-task-86ba1',
    storageBucket: 'quiz-app-task-86ba1.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrCb1u-KNgDYSv5WpUh7wGPWVodnBu6A',
    appId: '1:259171231904:ios:69573281e7551a9cfd01c5',
    messagingSenderId: '259171231904',
    projectId: 'quiz-app-task-86ba1',
    storageBucket: 'quiz-app-task-86ba1.appspot.com',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
